import type { Metadata } from 'next';
import { Be_Vietnam_Pro } from 'next/font/google';
import './globals.css';
import NavbarMain from '@/components/shared/Navbar/NavbarMain';
import { ThemeProvider } from 'next-themes';
import ReduxProvider from '@/providers/ReduxProvider';

const beVietnam = Be_Vietnam_Pro({
    variable: '--font-be-vietnam',
    subsets: ['latin'],
    weight: ['400', '500', '600', '700', '800', '900'], // Adjust as needed
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={`${beVietnam.variable} antialiased`}>
                <ThemeProvider
                    attribute='class' // This is crucial!
                    defaultTheme='system'
                    enableSystem={true}
                >
                    <div className='bg-background'>
                        <ReduxProvider>
                            <NavbarMain />
                            {children}
                        </ReduxProvider>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
